# This file was generated by https://github.com/kamilchm/go2nix v1.3.0
[
  {
    goPackagePath = "github.com/antihax/optional";
    fetch = {
      type = "git";
      url = "https://github.com/antihax/optional";
      rev = "ca021399b1a6796ecb758292c6311ce0b28857fc";
      sha256 = "1dn0d0rvcn0cx9hxpzzvixv5xc49lhdqd2apc6gqc9bq0c9aql60";
    };
  }
  {
    goPackagePath = "github.com/ellisdon-oss/azuredevops-go";
    fetch = {
      type = "git";
      url = "git@github.com:EllisDon-Aegean/azuredevops-go.git";
      rev = "f8e0b85e0171b09cb69047324491fdcf643e4bd3";
      sha256 = "0a699i1bzyfr6awpqjsvk8g2n4sv3wygvhnhdisc73c4j6xy0ryf";
    };
  }
  {
    goPackagePath = "github.com/hashicorp/terraform";
    fetch = {
      type = "git";
      url = "https://github.com/hashicorp/terraform";
      rev = "0728d1cefb99ebe4db465fe1ea647cb704ca4d4b";
      sha256 = "06bp43ri99kwiq3y0fwbcp8d5040hj1fmbk8bz27jdlwc2nd4c8b";
    };
  }
  {
    goPackagePath = "github.com/pkg/errors";
    fetch = {
      type = "git";
      url = "https://github.com/pkg/errors";
      rev = "059132a15dd08d6704c67711dae0cf35ab991756";
      sha256 = "0bxkbh2rq40kdk8i05am5np77cnskx3571v2k300j5mmj1rl1ijg";
    };
  }
  {
    goPackagePath = "golang.org/x/net";
    fetch = {
      type = "git";
      url = "https://go.googlesource.com/net";
      rev = "891ebc4b82d6e74f468c533b06f983c7be918a96";
      sha256 = "1rgw5gl2lc6bkmsx0fak84s6zdc1bhzfxgqg4mg4yh5hlnhpwrki";
    };
  }
  {
    goPackagePath = "golang.org/x/oauth2";
    fetch = {
      type = "git";
      url = "https://go.googlesource.com/oauth2";
      rev = "99b60b757ec124ebb7d6b7e97f153b19c10ce163";
      sha256 = "119py9nia7957kf51gg9qvh34d18jb1a293zwfgvdf5inl1ja6y6";
    };
  }
]
